export default [
  {
    path: '/',
    component: '../layouts/BlankLayout',
    routes: [
      {
        path: '/user',
        component: '../layouts/UserLayout',
        routes: [
          {
            path: '/user',
            redirect: '/user/login',
          },
          {
            name: '登录',
            path: '/user/login',
            component: './user/login',
          },
          {
            component: '404',
          },
        ],
      },
      {
        path: '/',
        component: '../layouts/BasicLayout',
        Routes: ['src/pages/Authorized'],
        // authority: ['admin', 'user'],
        routes: [
          {
            path: '/integratedKanban',
            name: '社区综合看板',
            icon: 'iconicon-test8',
            component: './integratedKanban',
            authority: 'sc:comprehensive:view',
          },
          {
            path: '/da',
            icon: 'iconicon-test4',
            name: '社区档案',
            authority: 'sc:archives:view',
            routes: [
              {
                path: '/da/search',
                name: '检索',
                icon: 'icontuoyuanxing1',
                component: './da/search',
                authority: 'sc:archives-search:view',
              },
              {
                path: '/da/search/:searchText',
                name: '检索详情',
                hideInMenu: true,
                component: './da/search/result',
                authority: 'sc:archives-search:view',
              },
              {
                path: '/da/residentFile',
                name: '社区居民档案',
                icon: 'icontuoyuanxing1',
                component: './da/residentFile',
                authority: 'sc:archives-resident:view',
              },
              {
                path: '/da/residentFile/detail',
                name: '社区居民详情',
                hideInMenu: true,
                component: './da/residentFile/residentDetail',
                authority: 'sc:archives-resident:view',
              },
              {
                path: '/da/residentFile/carDetail',
                name: '社区车辆详情',
                hideInMenu: true,
                component: './da/residentFile/carDetail',
                authority: 'sc:archives-resident:view',
              },
              {
                path: '/da/residentFile/carDetailForUnit',
                name: '社区单位车辆详情',
                hideInMenu: true,
                component: './da/institution/carDetail',
                authority: 'sc:archives-resident:view',
              },
              {
                path: '/da/residentFile/addResident',
                name: '添加居民',
                hideInMenu: true,
                component: './da/residentFile/residentEdit',
                authority: 'sc:archives-resident:view',
              },
              {
                path: '/da/residentFile/editResident',
                name: '编辑居民信息',
                hideInMenu: true,
                component: './da/residentFile/residentEdit',
                authority: 'sc:archives-resident:view',
              },
              {
                path: '/da/basicConstruction',
                name: '社区基础建设档案',
                icon: 'icontuoyuanxing1',
                component: './da/basicConstruction',
                authority: 'sc:archives-basic-bulid:view',
              },
              {
                path: '/da/basicFacility',
                name: '社区基础设施档案',
                icon: 'icontuoyuanxing1',
                component: './da/basicFacility',
                authority: 'sc:archives-basic-facilities:view',
              },
              {
                path: '/da/Institution',
                name: '社区实有单位档案',
                icon: 'icontuoyuanxing1',
                component: './da/institution',
                authority: 'sc:archives-unit:view',
              },
              {
                path: '/da/Institution/detail/:companyId/:urlContActiveKey',
                name: '单位信息详情',
                hideInMenu: true,
                component: './da/institution/detail',
                authority: 'sc:archives-unit:view',
              },
              {
                path: '/da/Institution/add',
                name: '添加单位',
                hideInMenu: true,
                component: './da/institution/addInstitution',
                authority: 'sc:archives-unit:view',
              },
              {
                path: '/da/Institution/edit/:companyId',
                name: ' 编辑单位',
                hideInMenu: true,
                component: './da/institution/editInstitution',
                authority: 'sc:archives-unit:view',
              },
              {
                path: '/da/Institution/addCarInfo',
                name: '添加车辆信息',
                hideInMenu: true,
                component: './da/institution/editCarInfo',
                authority: 'sc:archives-unit:view',
              },
              {
                path: '/da/Institution/editCarInfo',
                name: '编辑车辆信息',
                hideInMenu: true,
                component: './da/institution/editCarInfo',
                authority: 'sc:archives-unit:view',
              },
              {
                path: '/da/Institution/carDetail',
                name: '社区车辆详情',
                hideInMenu: true,
                component: './da/institution/carDetail',
                authority: 'sc:archives-unit:view',
              },
            ],
          },
          {
            name: '数据分析',
            path: '/dataAnalysis',
            icon: 'iconicon-test6',
            authority: 'sc:dataAnalysis:view',
            routes: [
              {
                name: '人车进出',
                path: '/dataAnalysis/turnover',
                icon: 'icontuoyuanxing1',
                component: './Welcome',
                authority: 'sc:dataAnalysis-rc-io:view',
              },
              {
                name: '实有房屋',
                path: '/dataAnalysis/house',
                icon: 'icontuoyuanxing1',
                component: './Welcome',
                authority: 'sc:dataAnalysis-house:view',
              },
              {
                name: '实有人口',
                path: '/dataAnalysis/population',
                icon: 'icontuoyuanxing1',
                component: './Welcome',
                authority: 'sc:dataAnalysis-person:view',
              },
              {
                name: '社区力量',
                path: '/dataAnalysis/power',
                icon: 'icontuoyuanxing1',
                component: './Welcome',
                authority: 'sc:dataAnalysis-res:view',
              },
            ],
          },
          {
            name: '安防监控',
            path: '/security',
            icon: 'iconicon-test10',
            authority: 'sc:monitor:view',
            routes: [
              {
                name: '设备监控',
                path: '/security/device',
                icon: 'icontuoyuanxing1',
                component: './Welcome',
                authority: 'sc:monitor-device:view',
              },
              {
                name: '视频监控',
                path: '/security/video',
                icon: 'icontuoyuanxing1',
                component: './Welcome',
                authority: 'sc:monitor-video:view',
              },
            ],
          },
          {
            name: '访客管理',
            path: '/visitor',
            icon: 'iconicon-test5',
            authority: 'sc:visitor:view',
            routes: [
              {
                name: '访客预约',
                path: '/visitor/reservation',
                icon: 'icontuoyuanxing1',
                component: './visitor/reservation',
                authority: 'sc:visitor-appointment:view',
              },
              {
                name: '访客登记',
                path: '/visitor/registration',
                icon: 'icontuoyuanxing1',
                component: './visitor/registration',
                authority: 'sc:visitor-register:view',
              },
            ],
          },
          {
            path: '/payment',
            icon: 'iconicon-test7',
            name: '生活缴费',
            authority: 'sc:payment:view',
            routes: [
              {
                path: '/payment/management',
                name: '物业费缴纳情况',
                icon: 'icontuoyuanxing1',
                component: './payment/management',
                authority: 'sc:payment-property:view',
              },
              {
                path: '/payment/management/detail/:parmas',
                name: '物业费缴纳记录详情',
                hideInMenu: true,
                component: './payment/management/detail',
                authority: 'sc:payment-property:view',
              },
              {
                path: '/payment/deposit',
                name: '押金缴纳记录',
                icon: 'icontuoyuanxing1',
                component: './payment/deposit',
                authority: 'sc:payment-deposit:view',
              },
              {
                path: '/payment/alimony',
                name: '生活缴费记录',
                icon: 'icontuoyuanxing1',
                component: './payment/alimony',
                authority: 'sc:payment-life:view',
              },
              {
                path: '/payment/parking',
                name: '停车费缴纳记录',
                icon: 'icontuoyuanxing1',
                component: './payment/parking',
                authority: 'sc:payment-park:view',
              },
              {
                path: '/payment/lifeManage',
                name: '生活缴费账号管理',
                icon: 'icontuoyuanxing1',
                component: './payment/lifeManage',
                authority: 'sc:payment-life:view',
              },
            ],
          },
          {
            path: '/communityService',
            icon: 'iconicon-test',
            name: '社区服务管理',
            authority: 'sc:service:view',
            routes: [
              {
                path: '/communityService/service',
                name: '社区服务',
                icon: 'icontuoyuanxing1',
                component: './communityService/service',
                authority: 'sc:service-ser:view',
              },
              {
                path: '/communityService/serviceType',
                name: '服务类型',
                icon: 'icontuoyuanxing1',
                component: './communityService/serviceType',
                authority: 'sc:service-type:view',
              },
              {
                path: '/communityService/service/addService',
                name: '新增服务',
                hideInMenu: true,
                component: './communityService/service/addService',
                authority: 'sc:service-type:view',
              },
              {
                path: '/communityService/service/addService/:id',
                name: '编辑服务',
                hideInMenu: true,
                component: './communityService/service/addService',
                authority: 'sc:service-type:view',
              },
              {
                path: '/communityService/service/detail/:id',
                name: '服务详情',
                hideInMenu: true,
                component: './communityService/service/detail',
                authority: 'sc:service-type:view',
              },
            ],
          },
          {
            path: '/earlyWarning',
            icon: 'iconicon-test18',
            name: '预警记录',
            authority: 'sc:alarm:view',
            routes: [
              {
                path: '/earlyWarning/parabolic',
                name: '高空抛物预警',
                icon: 'icontuoyuanxing1',
                component: './earlyWarning/parabolic',
                authority: 'sc:alarm-high-altitude:view',
              },
              {
                path: '/earlyWarning/focus',
                name: '重点关注预警',
                icon: 'icontuoyuanxing1',
                component: './earlyWarning/focus',
                authority: 'sc:alarm-major:view',
              },
              {
                path: '/earlyWarning/fence',
                name: '电子围栏报警',
                icon: 'icontuoyuanxing1',
                component: './earlyWarning/fence',
                authority: 'sc:alarm-electric-fence:view',
              },
              {
                path: '/earlyWarning/alarm',
                name: '居民报警',
                icon: 'icontuoyuanxing1',
                component: './earlyWarning/alarm',
                authority: 'sc:alarm-call:view',
              },
              {
                path: '/earlyWarning/smoke',
                name: '烟感报警',
                icon: 'icontuoyuanxing1',
                component: './earlyWarning/smoke',
                authority: 'sc:alarm-smoke:view',
              },
            ],
          },
          {
            path: '/patrol',
            icon: 'iconxingzhuang',
            name: '社区巡更',
            authority: 'sc:patrol:view',
            routes: [
              {
                path: '/patrol/monitor',
                name: '社区巡更监控',
                icon: 'icontuoyuanxing1',
                component: './Welcome',
                authority: 'sc:patrol-monitor:view',
              },
              {
                path: '/patrol/way',
                name: '巡更路线管理',
                icon: 'icontuoyuanxing1',
                component: './Welcome',
                authority: 'sc:patrol-line:view',
              },
              {
                path: '/patrol/task',
                name: '巡更任务',
                icon: 'icontuoyuanxing1',
                component: './Welcome',
                authority: 'sc:patrol-task:view',
              },
            ],
          },
          {
            path: '/trajectory',
            icon: 'iconicon-test9',
            name: '轨迹分析',
            authority: 'sc:travel:view',
            routes: [
              {
                path: '/trajectory/personnel',
                name: '人员轨迹',
                icon: 'icontuoyuanxing1',
                component: './Welcome',
                authority: 'sc:travel-person:view',
              },
              {
                path: '/trajectory/car',
                name: '车辆轨迹',
                icon: 'icontuoyuanxing1',
                component: './Welcome',
                authority: 'sc:travel-car:view',
              },
            ],
          },
          {
            path: '/infoBulletin',
            icon: 'iconicon-test3',
            name: '资讯公告',
            authority: 'sc:information:view',
            routes: [
              {
                path: '/infoBulletin/infoManage',
                name: '资讯管理',
                icon: 'icontuoyuanxing1',
                component: './infoBulletin/infoManage',
                authority: 'sc:information-manager:view',
              },
              {
                path: '/infoBulletin/infoManage/addInfo',
                name: '新增资讯',
                hideInMenu: true,
                component: './infoBulletin/infoManage/addInfo',
                authority: 'sc:information-manager:view',
              },
              {
                path: '/infoBulletin/infoManage/addInfo/:id',
                name: '编辑资讯',
                hideInMenu: true,
                component: './infoBulletin/infoManage/addInfo',
                authority: 'sc:information-manager:view',
              },
              {
                path: '/infoBulletin/infoManage/detail/:id',
                name: '资讯详情',
                hideInMenu: true,
                component: './infoBulletin/infoManage/detail',
                authority: 'sc:information-manager:view',
              },
              {
                path: '/infoBulletin/clumn',
                name: '栏目分类',
                icon: 'icontuoyuanxing1',
                component: './infoBulletin/clumn',
                authority: 'sc:information-type:view',
              },
            ],
          },
          {
            path: '/carouselMap',
            icon: 'iconicon-test3',
            name: '轮播图管理',
            authority: 'sc:carousel:view',
            routes: [
              {
                path: '/carouselMap/owner',
                name: '业主APP',
                icon: 'icontuoyuanxing1',
                component: './carouselMap/owner',
                authority: 'sc:yz-carousel:view',
              },
              {
                path: '/carouselMap/property',
                name: '物业APP',
                icon: 'icontuoyuanxing1',
                component: './carouselMap/owner',
                authority: 'sc:wy-carousel:view',
              },
            ],
          },
          {
            path: '/activity',
            icon: 'iconicon-test',
            name: '社区活动',
            authority: 'sc:activity:view',
            routes: [
              {
                path: '/activity/vote',
                name: '投票活动',
                icon: 'icontuoyuanxing1',
                component: './activity/vote',
                authority: 'sc:activity-vote:view',
              },
              {
                path: '/activity/vote/addActivity',
                name: '新增活动',
                hideInMenu: true,
                component: './activity/vote/addActivity',
                authority: 'sc:activity-vote:view',
              },
              {
                path: '/activity/vote/editActivity/:voteId',
                name: '编辑活动',
                hideInMenu: true,
                component: './activity/vote/editActivity',
                authority: 'sc:activity-vote:view',
              },
              {
                path: '/activity/vote/detail/:parmas',
                name: '活动详情',
                hideInMenu: true,
                component: './activity/vote/detail',
                authority: 'sc:activity-vote:view',
              },
              {
                path: '/activity/auditing',
                name: '居民活动审核',
                icon: 'icontuoyuanxing1',
                component: './activity/auditing',
                authority: 'sc:activity-audit:view',
              },
            ],
          },
          {
            path: '/residentAffairs',
            icon: 'iconicon-test2',
            name: '居民事务',
            authority: 'sc:event:view',
            routes: [
              {
                path: '/residentAffairs/report',
                name: '居民报事',
                icon: 'icontuoyuanxing1',
                component: './residentAffairs/report',
                authority: 'sc:event-repair:view',
              },
              {
                path: '/residentAffairs/complaint',
                name: '居民投诉',
                icon: 'icontuoyuanxing1',
                component: './residentAffairs/complaint',
                authority: 'sc:event-complaint:view',
              },
            ],
          },
          {
            path: '/audit',
            icon: 'iconicon-test11',
            name: '认证审核',
            authority: 'sc:identity:view',
            routes: [
              {
                path: '/audit/resident',
                name: '居民认证',
                icon: 'icontuoyuanxing1',
                component: './audit/resident',
                authority: 'sc:identity-resident:view',
              },
              {
                path: '/audit/buildings',
                name: '房屋认证',
                icon: 'icontuoyuanxing1',
                component: './audit/buildings',
                authority: 'sc:identity-house:view',
              },
              {
                path: '/audit/vehicle',
                name: '车辆认证',
                icon: 'icontuoyuanxing1',
                component: './audit/vehicle',
                authority: 'sc:identity-car:view',
              },
            ],
          },
          {
            path: '/system',
            icon: 'iconxitongguanli_',
            name: '系统管理',
            authority: 'sc:sysManager:view',
            routes: [
              {
                path: '/system/department',
                name: '部门管理',
                icon: 'icontuoyuanxing1',
                component: './system/department',
                authority: 'sc:sysManager-dept:view',
              },
              {
                path: '/system/manager',
                name: '社区组织管理人员',
                icon: 'icontuoyuanxing1',
                component: './system/organization',
                authority: 'sc:sysManager-manager-person:view',
              },
              {
                path: '/system/user',
                name: '用户管理',
                icon: 'icontuoyuanxing1',
                component: './system/user',
                authority: 'sc:sysManager-user:view',
              },
              {
                path: '/system/role',
                name: '角色管理',
                icon: 'icontuoyuanxing1',
                component: './system/role',
                authority: 'sc:sysManager-role:view',
              },
              {
                path: '/system/log',
                name: '系统日志',
                icon: 'icontuoyuanxing1',
                component: './system/log',
                authority: 'sc:sysManager-log:view',
              },
              {
                path: '/system/letter',
                name: '站内信',
                icon: 'icontuoyuanxing1',
                component: './system/letter',
                authority: 'sc:sysManager-message:view',
              },
              {
                path: '/system/letter/detail/:messageId',
                name: '详情',
                hideInMenu: true,
                component: './system/letter/detail',
                authority: 'sc:sysManager-message:view',
              },
            ],
          },
          {
            path: '/account',
            icon: 'iconicon-test3',
            name: '个人中心',
            hideInMenu: true,
            routes: [
              {
                path: '/account/resetPwd',
                name: '修改密码',
                icon: 'icontuoyuanxing1',
                component: './account/resetPwd',
              },
            ],
          },
          {
            path: '/',
            redirect: '/integratedKanban',
            // authority: ['admin', 'user'],
          },
          {
            component: '404',
          },
        ],
      },
    ],
  },
];
